## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [3]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
ss = np.array([2.5]*10)
ss

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
ss = np.full(10, 2.5)
ss

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [6]:
ss = np.array([ 1 if idx == 4 else 0 for idx in range(10)])
ss

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [7]:
ss = np.zeros(10)
ss[4] = 1
ss

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [8]:
bb = np.arange(50)
bb = bb[::-1]
bb

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [9]:
cc = np.arange(9).reshape((3,3))
cc

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [12]:
items = [1,2,0,0,4,0]

def get_idx_zero(items):
    return [idx for idx, v in enumerate(items) if v != 0]

indices = get_idx_zero(items)
indices

[0, 1, 4]

In [13]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [15]:
np.array(list(map(lambda x: np.random.normal(), range(3*3*3)))).reshape((3,3,3))

array([[[ 0.62293225,  0.16510656, -1.65424695],
        [-0.31398375,  0.80448191, -0.71734681],
        [ 0.69748235, -3.04644356, -0.47218337]],

       [[ 0.00730122,  0.16402394,  0.13992481],
        [ 0.59192039, -1.07962326, -2.3136927 ],
        [ 0.85036226, -0.28675638, -1.2938589 ]],

       [[-1.59099902, -0.88520316,  0.15022791],
        [ 0.14694282,  1.17295902,  0.21776803],
        [ 0.16275175, -0.83316694, -0.38784202]]])

In [16]:
np.random.random((3,3,3))

array([[[0.34660701, 0.35901878, 0.661967  ],
        [0.95846728, 0.96322018, 0.55210041],
        [0.22526288, 0.11303466, 0.08021633]],

       [[0.65261903, 0.90185991, 0.04152734],
        [0.04766264, 0.20333464, 0.25488285],
        [0.23945625, 0.61072667, 0.52992103]],

       [[0.09971176, 0.65322232, 0.17249684],
        [0.81657194, 0.60953545, 0.2873841 ],
        [0.06221192, 0.16142004, 0.25007738]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [17]:
np.random.random(30).mean()

0.476667731466777

Перемножить матрицы 5x3 и 3x2

In [18]:
np.dot(np.random.random((5,3)), np.random.random((3,2)))

array([[0.29003316, 0.63088415],
       [0.86345461, 1.06992653],
       [0.24823925, 0.78111113],
       [0.49164932, 0.84328579],
       [0.92481858, 1.18969304]])

In [19]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [20]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [21]:
qq = np.random.random(10)
print(qq, qq.argmax())
qq[qq.argmax()] = 0
print(qq, qq.argmax())

[0.34589837 0.40244005 0.90211599 0.84993723 0.35480564 0.766462
 0.21927754 0.94266197 0.29983366 0.78426761] 7
[0.34589837 0.40244005 0.90211599 0.84993723 0.35480564 0.766462
 0.21927754 0.         0.29983366 0.78426761] 2


Преобразовать массив из float в int

In [22]:
np.arange(10, dtype=np.float16).astype(np.int16, copy=False)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [24]:
from scipy.spatial import distance
qq = np.random.random((10, 2))
distance.cdist(qq,qq)

array([[0.        , 0.38356427, 0.62694242, 0.51758908, 0.51436226,
        0.51589689, 0.57477721, 0.74424384, 0.42636042, 0.61128396],
       [0.38356427, 0.        , 0.44654057, 0.32532299, 0.46542523,
        0.23586727, 0.2071266 , 0.36115417, 0.09749681, 0.45602386],
       [0.62694242, 0.44654057, 0.        , 0.76824491, 0.19000104,
        0.66368132, 0.36630277, 0.51314325, 0.35169028, 0.0386748 ],
       [0.51758908, 0.32532299, 0.76824491, 0.        , 0.7860537 ,
        0.12152574, 0.45241821, 0.48885266, 0.4167687 , 0.78013349],
       [0.51436226, 0.46542523, 0.19000104, 0.7860537 , 0.        ,
        0.70083465, 0.46902565, 0.64586577, 0.39051348, 0.15373325],
       [0.51589689, 0.23586727, 0.66368132, 0.12152574, 0.70083465,
        0.        , 0.33347397, 0.37137167, 0.31668084, 0.67881373],
       [0.57477721, 0.2071266 , 0.36630277, 0.45241821, 0.46902565,
        0.33347397, 0.        , 0.19109677, 0.15025052, 0.39185024],
       [0.74424384, 0.36115417, 0.5131432

Случайно расположить p элементов в 2D массив

In [49]:
p_num = 36
row_size = 8
p = np.random.randint(0, 100, p_num)
auto_add_zero = lambda x: x if not len(x) % row_size else np.append(x, [0.]*(row_size - len(x) % row_size))
p = auto_add_zero(p)
array1 = np.array(p)
array1.reshape(row_size, int(len(p)/row_size))

array([[77., 85.,  9.,  6., 42.],
       [21., 61.,  7., 77., 86.],
       [71., 52., 49.,  8., 42.],
       [ 2., 10., 18., 17., 75.],
       [47., 12., 55., 92., 67.],
       [71., 70., 19., 95., 12.],
       [40., 89., 40., 12., 65.],
       [71.,  0.,  0.,  0.,  0.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [52]:
from functools import reduce
ss = [1, 2, 3, 4, 5]
n_zeros = 3
qq = np.array(list(
    reduce((lambda x, y: x + [y] + [0]*n_zeros if x and isinstance(x, list) else [x] + [0]*n_zeros), ss)))
qq

array([1, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

Найти наиболее частое значение в массиве

In [53]:
qq = np.random.randint(0, 10, 50)
tt = np.bincount(qq)
print(qq)
print("dublicates num:" , qq[tt.argmax()]," times:",tt.max())

[5 0 3 7 2 5 4 8 1 4 3 4 5 6 8 4 5 2 4 0 8 6 0 0 5 7 6 8 0 8 6 3 3 2 7 0 4
 5 2 3 1 7 5 5 5 6 3 0 9 8]
dublicates num: 5  times: 9


Найти n наибольших значений в массиве

In [54]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [29]:
import pandas as pd
import numpy as np

food = pd.read_csv("~/Documents/lectures/lecture-02_math/en.openfoodfacts.org.products.tsv/en.openfoodfacts.org.products.tsv" , sep='\t')

/home/duko/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [30]:
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [31]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [32]:
food.shape[1]

163

Напечатайте все названия столбцов

In [33]:
food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [34]:
food.columns[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [35]:
food.dtypes[df.columns[105]]

dtype('float64')

Как проиндексирован набор данных?

In [36]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [37]:
food.values[18][7]

'Lotus Organic Brown Jasmine Rice'

In [38]:
del food

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [40]:
chipo = pd.read_csv("chipotle.tsv", sep='\t')

Как много продуктов стоят более чем $10.00?

In [84]:
chipo['new_item_price'] = chipo['item_price'].str[1:].astype("float32")
chipo['new_item_price'][chipo['new_item_price'] > 10].count()

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [103]:
items = chipo.drop_duplicates(subset=['item_name'], keep='last')
items['one_cost'] = items['new_item_price'] / items['quantity']
items[['item_name','quantity', 'item_price', 'one_cost']].sort_values('item_name')

/home/duko/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


item_name  quantity item_price  one_cost
4535                      6 Pack Soft Drink         1     $6.49       6.49
4594                          Barbacoa Bowl         1    $11.75      11.75
4603                       Barbacoa Burrito         1     $9.25       9.25
3321                  Barbacoa Crispy Tacos         1     $8.99       8.99
4390                    Barbacoa Salad Bowl         1     $9.39       9.39
4271                    Barbacoa Soft Tacos         1     $9.25       9.25
4614                          Bottled Water         1     $1.50       1.50
673                                    Bowl         1     $7.40       7.40
760                                 Burrito         1     $7.40       7.40
4051                            Canned Soda         1     $1.09       1.09
4609                      Canned Soft Drink         1     $1.25       1.25
4612                          Carnitas Bowl         1     $9.25       9.25
4578                       Carnitas Burrito         1     $9.25       9.25
4450                  Carnitas Crispy Tacos         1     $9.25       9.25
3750                         Carnitas Salad         1     $8.99       8.99
4239                    Carnitas Salad Bowl         1    $11.89      11.89
4557                    Carnitas Soft Tacos         1     $9.25       9.25
4604                           Chicken Bowl         1     $8.75       8.75
4569                        Chicken Burrito         1     $8.75       8.75
4453                   Chicken Crispy Tacos         1     $8.75       8.75
3989                          Chicken Salad         1     $8.19       8.19
4621                     Chicken Salad Bowl         1     $8.75       8.75
4615                     Chicken Soft Tacos         1     $8.75       8.75
4613                                  Chips         1     $2.15       2.15
4503           Chips and Fresh Tomato Salsa         1     $2.95       2.95
4616                    Chips and Guacamole         1     $4.45       4.45
674       Chips and Mild Fresh Tomato Salsa         1     $3.00       3.00
3780     Chips and Roasted Chili Corn Salsa         1     $2.95       2.95
3905     Chips and Roasted Chili-Corn Salsa         1     $2.39       2.39
4493  Chips and Tomatillo Green Chili Salsa         1     $2.95       2.95
4466    Chips and Tomatillo Red Chili Salsa         1     $2.95       2.95
4007  Chips and Tomatillo-Green Chili Salsa         1     $2.39       2.39
4088    Chips and Tomatillo-Red Chili Salsa         1     $2.39       2.39
521                            Crispy Tacos         1     $7.40       7.40
3669                                   Izze         1     $3.39       3.39
4078                       Nantucket Nectar         1     $3.39       3.39
1415                                  Salad         1     $7.40       7.40
4070                          Side of Chips         1     $1.69       1.69
4518                             Steak Bowl         1    $11.75      11.75
4618                          Steak Burrito         1    $11.75      11.75
4554                     Steak Crispy Tacos         1    $11.75      11.75
3502                            Steak Salad         1     $8.69       8.69
4572                       Steak Salad Bowl         1     $9.39       9.39
4549                       Steak Soft Tacos         1     $9.25       9.25
4468                            Veggie Bowl         1    $11.25      11.25
4611                         Veggie Burrito         1    $11.25      11.25
1653                    Veggie Crispy Tacos         1     $8.49       8.49
4084                           Veggie Salad         1     $8.49       8.49
4573                      Veggie Salad Bowl         1     $8.75       8.75
3889                      Veggie Soft Tacos         2    $16.98       8.49

Отсортировать по имени предмета

In [93]:
chipo.sort_values('item_name')

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  \
3389                                        [Diet Coke]    $12.98    
341                                         [Diet Coke]     $6.49    
1849                                             [Coke]     $6.49    
1860                                        [Diet Coke]     $6.49    
2713                                             [Coke]     $6.49    
3422                                             [Coke]     $6.49    
553                                         [Diet Coke]     $6.49    
1916                                        [Diet Coke]     $6.49    
1922                                             [Coke]     $6.49    
1937                                        [Diet Coke]     $6.49    
3836                                             [Coke]     $6.49    
298                                            [Sprite]     $6.49    
1976                                        [Diet Coke]     $6.49    
1167                                             [Coke]     $6.49    
3875                                     

Сколько было заказано самого дорогого предмета?

In [113]:
top_item = items['item_name'][items['one_cost'].argmax()]
print(top_item, chipo['quantity'][chipo['item_name'] == top_item].sum())
chipo[chipo['item_name'] == top_item]

Carnitas Salad Bowl 6


order_id  quantity            item_name  \
1132       468         1  Carnitas Salad Bowl   
1865       756         1  Carnitas Salad Bowl   
2610      1035         1  Carnitas Salad Bowl   
3115      1243         1  Carnitas Salad Bowl   
3749      1499         1  Carnitas Salad Bowl   
4239      1692         1  Carnitas Salad Bowl   

                                     choice_description item_price  \
1132  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...    $11.89    
1865   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]     $9.39    
2610  [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $11.89    
3115  [Tomatillo Green Chili Salsa, [Rice, Pinto Bea...     $9.39    
3749  [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $11.89    
4239  [Tomatillo Green Chili Salsa, [Black Beans, Ch...    $11.89    

      new_item_price  
1132           11.89  
1865            9.39  
2610           11.89  
3115            9.39  
3749           11.89  
4239           11.89

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [124]:
print("Veggie Salad Bowl", 
      chipo['item_name'][chipo.item_name == "Veggie Salad Bowl"].count())

Veggie Salad Bowl 18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [126]:
print("Canned Soda", 
      chipo['quantity'][(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)].count())
# chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]

Canned Soda 20
